// packages/ui/src/components/ui/badge.tsx
import * as React from 'react'

import { cn } from '../../lib/utils'

type BadgeVariant = 'default' | 'secondary' | 'destructive' | 'outline' | 'ghost' | 'link'

export interface BadgeProps extends React.HTMLAttributes<HTMLSpanElement> {
  variant?: BadgeVariant
}

const badgeClassByVariant: Record<BadgeVariant, string> = {
  default: 'ui-badge--default',
  secondary: 'ui-badge--secondary',
  destructive: 'ui-badge--destructive',
  outline: 'ui-badge--outline',
  ghost: 'ui-badge--ghost',
  link: 'ui-badge--link',
}

function Badge({
  className,
  variant = 'default',
  ...props
}: BadgeProps) {
  return (
    <span
      className={cn('ui-badge', badgeClassByVariant[variant], className)}
      {...props}
    />
  )
}

export { Badge }

// packages/ui/src/components/ui/Badge.vue
<script setup lang="ts">
import { computed } from 'vue'

const props = withDefaults(defineProps<{
  variant?: 'default' | 'secondary' | 'destructive' | 'outline' | 'ghost' | 'link'
}>(), {
  variant: 'default',
})

const classes = computed(() => ['ui-badge', `ui-badge--${props.variant}`])
</script>

<template>
  <span :class="classes">
    <slot />
  </span>
</template>
