// packages/ui/src/components/ui/switch.tsx
import * as React from 'react'

import { cn } from '../../lib/utils'

export interface SwitchProps extends Omit<React.ButtonHTMLAttributes<HTMLButtonElement>, 'onChange'> {
  checked?: boolean
  defaultChecked?: boolean
  onCheckedChange?: (checked: boolean) => void
  size?: 'sm' | 'default'
}

const Switch = React.forwardRef<HTMLButtonElement, SwitchProps>((
  {
    checked,
    className,
    defaultChecked = false,
    disabled,
    onCheckedChange,
    onClick,
    size = 'default',
    type = 'button',
    ...props
  },
  ref,
) => {
  const [internalChecked, setInternalChecked] = React.useState(defaultChecked)
  const isControlled = typeof checked === 'boolean'
  const isChecked = isControlled ? checked : internalChecked

  const handleClick = (event: React.MouseEvent<HTMLButtonElement>) => {
    onClick?.(event)
    if (event.defaultPrevented || disabled)
      return

    const nextChecked = !isChecked
    if (!isControlled)
      setInternalChecked(nextChecked)
    onCheckedChange?.(nextChecked)
  }

  return (
    <button
      ref={ref}
      aria-checked={isChecked}
      className={cn(
        'ui-switch',
        size === 'sm' ? 'ui-switch--sm' : 'ui-switch--default',
        isChecked && 'is-checked',
        disabled && 'is-disabled',
        className,
      )}
      disabled={disabled}
      role="switch"
      type={type}
      onClick={handleClick}
      {...props}
    >
      <span className="ui-switch__thumb" />
    </button>
  )
})

export { Switch }

// packages/ui/src/components/ui/Switch.vue
<script setup lang="ts">
import { computed, ref, useAttrs, watch } from 'vue'

defineOptions({
  inheritAttrs: false,
})

const props = withDefaults(defineProps<{
  checked?: boolean
  defaultChecked?: boolean
  disabled?: boolean
  size?: 'sm' | 'default'
}>(), {
  checked: undefined,
  defaultChecked: false,
  disabled: false,
  size: 'default',
})

const emit = defineEmits<{
  (event: 'update:checked', value: boolean): void
  (event: 'checked-change', value: boolean): void
}>()

const attrs = useAttrs()
const internalChecked = ref(props.defaultChecked)

watch(() => props.defaultChecked, (value) => {
  if (props.checked === undefined) {
    internalChecked.value = value
  }
})

const currentChecked = computed(() => (props.checked === undefined ? internalChecked.value : props.checked))

const classes = computed(() => [
  'ui-switch',
  props.size === 'sm' ? 'ui-switch--sm' : 'ui-switch--default',
  currentChecked.value && 'is-checked',
  props.disabled && 'is-disabled',
])

function toggle() {
  if (props.disabled)
    return

  const nextChecked = !currentChecked.value
  if (props.checked === undefined) {
    internalChecked.value = nextChecked
  }
  emit('update:checked', nextChecked)
  emit('checked-change', nextChecked)
}
</script>

<template>
  <button
    v-bind="attrs"
    :aria-checked="currentChecked"
    :class="classes"
    :disabled="disabled"
    role="switch"
    type="button"
    @click="toggle"
  >
    <span class="ui-switch__thumb" />
  </button>
</template>
